import { db } from "./db";
import { categories, products, users, stores } from "@shared/schema";

export async function seedDatabase() {
  try {
    console.log("Seeding database...");

    // Check if data already exists
    const existingCategories = await db.select().from(categories);
    if (existingCategories.length > 0) {
      console.log("Database already seeded");
      return;
    }

    // Create categories for daily essentials
    const categoryData = [
      {
        name: "Cooking Oils & Ghee",
        nameHindi: "खाना पकाने का तेल और घी",
        slug: "cooking-oils",
        description: "Essential cooking oils, ghee, and butter",
        image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5",
        isActive: true,
        sortOrder: 1,
      },
      {
        name: "Rice & Grains",
        nameHindi: "चावल और अनाज",
        slug: "rice-grains",
        description: "All types of rice, wheat, and grains",
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c",
        isActive: true,
        sortOrder: 2,
      },
      {
        name: "Pulses & Lentils",
        nameHindi: "दाल और दलहन",
        slug: "pulses-lentils",
        description: "Various types of dal and pulses",
        image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b",
        isActive: true,
        sortOrder: 3,
      },
      {
        name: "Spices & Masala",
        nameHindi: "मसाले",
        slug: "spices-masala",
        description: "Essential Indian spices and masalas",
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4",
        isActive: true,
        sortOrder: 4,
      },
      {
        name: "Tea, Coffee & Beverages",
        nameHindi: "चाय, कॉफी और पेय",
        slug: "tea-coffee",
        description: "Tea, coffee, and other beverages",
        image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574",
        isActive: true,
        sortOrder: 5,
      },
      {
        name: "Sugar & Salt",
        nameHindi: "चीनी और नमक",
        slug: "sugar-salt",
        description: "Sugar, salt, and sweeteners",
        image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b",
        isActive: true,
        sortOrder: 6,
      },
      {
        name: "Soap & Personal Care",
        nameHindi: "साबुन और व्यक्तिगत देखभाल",
        slug: "soap-personal-care",
        description: "Bath soaps, personal hygiene products",
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03",
        isActive: true,
        sortOrder: 7,
      },
      {
        name: "Cleaning & Household",
        nameHindi: "सफाई और घरेलू सामान",
        slug: "cleaning-household",
        description: "Cleaning products and household items",
        image: "https://images.unsplash.com/photo-1563453392212-326f5e854473",
        isActive: true,
        sortOrder: 8,
      },
      {
        name: "Fresh Vegetables",
        nameHindi: "ताज़ी सब्जियां",
        slug: "fresh-vegetables",
        description: "Daily fresh vegetables",
        image: "https://images.unsplash.com/photo-1590779033100-9f60a05a013d",
        isActive: true,
        sortOrder: 9,
      },
      {
        name: "Fresh Fruits",
        nameHindi: "ताज़े फल",
        slug: "fresh-fruits",
        description: "Seasonal fresh fruits",
        image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf",
        isActive: true,
        sortOrder: 10,
      }
    ];

    // Insert categories
    const insertedCategories = await db.insert(categories).values(categoryData).returning();
    console.log(`Inserted ${insertedCategories.length} categories`);

    // Create a sample seller user
    const sellerUser = await db.insert(users).values({
      email: "seller@shopnish.com",
      password: "password123",
      firstName: "Raj",
      lastName: "Kumar",
      phone: "9876543210",
      role: "seller",
      address: "Shop No. 15, Main Market",
      city: "Jaipur",
      pincode: "302001",
      isActive: true,
    }).returning();

    // Create a sample store
    const sampleStore = await db.insert(stores).values({
      sellerId: sellerUser[0].id,
      storeName: "Kumar General Store",
      storeType: "grocery",
      address: "Shop No. 15, Main Market, Pink City",
      city: "Jaipur",
      pincode: "302001",
      phone: "9876543210",
      isActive: true,
      licenseNumber: "RAJ-GRO-2024-001",
      gstNumber: "08ABCDE1234F1Z5",
    }).returning();

    // Create sample products for daily essentials
    const productData = [
      // Cooking Oils
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[0].id,
        name: "Fortune Sunflower Oil",
        nameHindi: "फॉर्च्यून सूरजमुखी तेल",
        description: "Pure sunflower oil for healthy cooking",
        descriptionHindi: "स्वस्थ खाना पकाने के लिए शुद्ध सूरजमुखी तेल",
        price: "185.00",
        originalPrice: "195.00",
        image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5",
        images: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5"],
        unit: "1L",
        brand: "Fortune",
        stock: 50,
        minOrderQty: 1,
        maxOrderQty: 5,
        isActive: true,
      },
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[0].id,
        name: "Amul Pure Ghee",
        nameHindi: "अमूल शुद्ध घी",
        description: "Pure cow ghee for traditional cooking",
        descriptionHindi: "पारंपरिक खाना पकाने के लिए शुद्ध गाय का घी",
        price: "275.00",
        image: "https://images.unsplash.com/photo-1628288506630-024db3db8216",
        images: ["https://images.unsplash.com/photo-1628288506630-024db3db8216"],
        unit: "500ml",
        brand: "Amul",
        stock: 30,
        minOrderQty: 1,
        maxOrderQty: 3,
        isActive: true,
      },

      // Rice & Grains
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[1].id,
        name: "India Gate Basmati Rice",
        nameHindi: "इंडिया गेट बासमती चावल",
        description: "Premium quality basmati rice",
        descriptionHindi: "प्रीमियम गुणवत्ता बासमती चावल",
        price: "145.00",
        originalPrice: "155.00",
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c",
        images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c"],
        unit: "1kg",
        brand: "India Gate",
        stock: 100,
        minOrderQty: 1,
        maxOrderQty: 10,
        isActive: true,
      },
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[1].id,
        name: "Whole Wheat Flour",
        nameHindi: "पूरे गेहूं का आटा",
        description: "Fresh ground whole wheat flour",
        descriptionHindi: "ताजा पिसा हुआ पूरे गेहूं का आटा",
        price: "45.00",
        image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b",
        images: ["https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b"],
        unit: "1kg",
        brand: "Local Mill",
        stock: 80,
        minOrderQty: 1,
        maxOrderQty: 20,
        isActive: true,
      },

      // Pulses & Lentils
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[2].id,
        name: "Toor Dal",
        nameHindi: "तूर दाल",
        description: "High quality yellow pigeon peas",
        descriptionHindi: "उच्च गुणवत्ता वाली पीली अरहर दाल",
        price: "85.00",
        image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b",
        images: ["https://images.unsplash.com/photo-1559181567-c3190ca9959b"],
        unit: "1kg",
        brand: "Premium",
        stock: 60,
        minOrderQty: 1,
        maxOrderQty: 5,
        isActive: true,
      },
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[2].id,
        name: "Moong Dal",
        nameHindi: "मूंग दाल",
        description: "Split yellow gram lentils",
        descriptionHindi: "पीली मूंग दाल",
        price: "95.00",
        image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b",
        images: ["https://images.unsplash.com/photo-1559181567-c3190ca9959b"],
        unit: "1kg",
        brand: "Premium",
        stock: 45,
        minOrderQty: 1,
        maxOrderQty: 5,
        isActive: true,
      },

      // Spices
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[3].id,
        name: "MDH Garam Masala",
        nameHindi: "एमडीएच गरम मसाला",
        description: "Traditional blend of aromatic spices",
        descriptionHindi: "सुगंधित मसालों का पारंपरिक मिश्रण",
        price: "35.00",
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4",
        images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4"],
        unit: "50g",
        brand: "MDH",
        stock: 75,
        minOrderQty: 1,
        maxOrderQty: 10,
        isActive: true,
      },
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[3].id,
        name: "Red Chili Powder",
        nameHindi: "लाल मिर्च पाउडर",
        description: "Pure red chili powder",
        descriptionHindi: "शुद्ध लाल मिर्च पाउडर",
        price: "65.00",
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4",
        images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4"],
        unit: "200g",
        brand: "Local",
        stock: 40,
        minOrderQty: 1,
        maxOrderQty: 5,
        isActive: true,
      },

      // Tea & Coffee
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[4].id,
        name: "Tata Tea Gold",
        nameHindi: "टाटा टी गोल्ड",
        description: "Premium quality black tea",
        descriptionHindi: "प्रीमियम गुणवत्ता काली चाय",
        price: "155.00",
        image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574",
        images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574"],
        unit: "500g",
        brand: "Tata",
        stock: 35,
        minOrderQty: 1,
        maxOrderQty: 5,
        isActive: true,
      },

      // Sugar & Salt
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[5].id,
        name: "Refined Sugar",
        nameHindi: "साफ़ चीनी",
        description: "Pure white refined sugar",
        descriptionHindi: "शुद्ध सफेद रिफाइंड चीनी",
        price: "42.00",
        image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b",
        images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b"],
        unit: "1kg",
        brand: "Local",
        stock: 90,
        minOrderQty: 1,
        maxOrderQty: 10,
        isActive: true,
      },
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[5].id,
        name: "Tata Salt",
        nameHindi: "टाटा नमक",
        description: "Iodized refined salt",
        descriptionHindi: "आयोडीन युक्त रिफाइंड नमक",
        price: "22.00",
        image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b",
        images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b"],
        unit: "1kg",
        brand: "Tata",
        stock: 85,
        minOrderQty: 1,
        maxOrderQty: 10,
        isActive: true,
      },

      // Personal Care
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[6].id,
        name: "Lifebuoy Soap",
        nameHindi: "लाइफबॉय साबुन",
        description: "Antibacterial protection soap",
        descriptionHindi: "एंटीबैक्टीरियल सुरक्षा साबुन",
        price: "35.00",
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03",
        images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03"],
        unit: "125g",
        brand: "Lifebuoy",
        stock: 120,
        minOrderQty: 1,
        maxOrderQty: 20,
        isActive: true,
      },

      // Vegetables
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[8].id,
        name: "Fresh Onions",
        nameHindi: "ताज़ा प्याज",
        description: "Daily fresh red onions",
        descriptionHindi: "दैनिक ताज़ा लाल प्याज",
        price: "28.00",
        image: "https://images.unsplash.com/photo-1590779033100-9f60a05a013d",
        images: ["https://images.unsplash.com/photo-1590779033100-9f60a05a013d"],
        unit: "1kg",
        brand: "Farm Fresh",
        stock: 50,
        minOrderQty: 1,
        maxOrderQty: 10,
        isActive: true,
      },
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[8].id,
        name: "Fresh Tomatoes",
        nameHindi: "ताज़े टमाटर",
        description: "Ripe red tomatoes",
        descriptionHindi: "पके हुए लाल टमाटर",
        price: "35.00",
        image: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337",
        images: ["https://images.unsplash.com/photo-1546094096-0df4bcaaa337"],
        unit: "1kg",
        brand: "Farm Fresh",
        stock: 40,
        minOrderQty: 1,
        maxOrderQty: 8,
        isActive: true,
      },

      // Fruits
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[9].id,
        name: "Fresh Bananas",
        nameHindi: "ताज़े केले",
        description: "Ripe yellow bananas",
        descriptionHindi: "पके हुए पीले केले",
        price: "45.00",
        image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf",
        images: ["https://images.unsplash.com/photo-1610832958506-aa56368176cf"],
        unit: "1 dozen",
        brand: "Farm Fresh",
        stock: 30,
        minOrderQty: 1,
        maxOrderQty: 5,
        isActive: true,
      },
      {
        sellerId: sellerUser[0].id,
        storeId: sampleStore[0].id,
        categoryId: insertedCategories[9].id,
        name: "Fresh Apples",
        nameHindi: "ताज़े सेब",
        description: "Crisp red apples",
        descriptionHindi: "कुरकुरे लाल सेब",
        price: "140.00",
        image: "https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a",
        images: ["https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a"],
        unit: "1kg",
        brand: "Farm Fresh",
        stock: 25,
        minOrderQty: 1,
        maxOrderQty: 5,
        isActive: true,
      }
    ];

    // Insert products
    const insertedProducts = await db.insert(products).values(productData).returning();
    console.log(`Inserted ${insertedProducts.length} products`);

    console.log("Database seeded successfully!");
    
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}